export const Theme = {
    palette: {
        greenLight: '#55efc4',
        greenHard: '#00b894',
        yellowLight: '#ffeaa7',
        yellowHard: '#fdcb6e',
        blueVeryLight: '#81ecec',
        blueLight: '#81ecec',
        blue: '#74b9ff',
        blueDark: '#0984e3',
        orangeLight: '#fab1a0',
        orangeHard: '#e17055',
        redLight: '#ff7675',
        redHard: '#d63031',
        purpleLight: '#a29bfe',
        purpleHard: '#6c5ce7',
        pinkLight: '#fd79a8',
        pinkHard: '#e84393',
        whiteFaded: '#e6edf0',
        grayLight: '#dfe6e9',
        gray: '#b2bec3',
        grayDark: '#636e72',
        blackFaded: '#2d3436',
    },
    margins: {
        sizeVerySmall: '4px',
        sizeSmall: '6px',
        sizeNormal: '8px',
        sizeBig: '12px',
        sizeBigger: '16px',
        sizeLarger: '18px',
        sizeLargest: '22px',
        sizeHuge: '24px',
    },
    fontSizes: {
        sizeSmall: '10px',
        sizeNormal: '12px',
        sizeBig: '14px',
        sizeBigger: '16px',
        sizeEmphasized: '18px',
    }
};
